[WIP] add Python3.9 + Django 2.2 support
beproud/bpmailer pull request #13
Opened 2022-03-04 07:53 UTC by imaxyz

2022-03-09 02:16 UTC, imaxyz commented on tests.py
> +    failures = test_runner.run_tests(['beproud.django.mailer.tests'])
Djangoのrun_tests()メソッドのドキュメントを参考に、テストモジュールへのPathを微修正しました。

> Test labels should be dotted Python paths to test modules, test classes, or test methods.

https://github.com/django/django/blob/e541f2d05b88e58c18b82b622aacc38d670eb5f6/django/test/runner.py#L618

2022-03-10 06:08 UTC, shimizukawa requested changes
MUSTあります

2022-03-10 06:08 UTC, shimizukawa commented on .github/workflows/tests.yml
> +        python-version: [3.6, 3.9]
ASK: 2.7もtox.iniやREADME.mdに書かれていますが、ここに無いのは意図的ですか？

2022-03-10 06:08 UTC, shimizukawa commented on .github/workflows/tests.yml
> +      matrix:
ASK: djangoはmatrixにしないんですか？

2022-03-10 06:08 UTC, shimizukawa commented on tests.py
> +    failures = test_runner.run_tests(['beproud.django.mailer.tests'])
MUST: レビューのために、この修正の妥当性の説明が欲しいです。

> (Djangoのバージョンが変わったためか?) 

確信はないけどこうしたら動いた、ということでしょうか。

2022-03-10 06:10 UTC, kashewnuts requested changes
@imaxyz コメントしました。

2022-03-10 06:10 UTC, kashewnuts commented on tox.ini
> +envlist = py27-django111, py36-django{111,22}, py39-django22
SHOULD: Python2.7とDjango1.11はEOLなので削除したいです。Django3.2対応は別途かな...
```suggestion
envlist =  py{36,39}-django22
```

2022-03-10 06:10 UTC, kashewnuts commented on tests.py
> +    failures = test_runner.run_tests(['beproud.django.mailer.tests'])
原因はsetuptoolsの更新のためのようです。 変更自体はまずはこれでよさそう。
* https://github.com/pypa/setuptools/pull/2523
* https://setuptools.pypa.io/en/latest/history.html#v51-2-0 →同様のエラーが発生する
* https://setuptools.pypa.io/en/latest/history.html#v51-1-2 →発生しない

このPRで対応するかは任せますが、 `python setup.py test` コマンド自体が非推奨になっているのでpytestに置き換えた方がよさそうです。 https://setuptools.pypa.io/en/latest/userguide/commands.html?highlight=test_suite#test-build-package-and-run-a-unittest-suite

2022-03-10 06:10 UTC, kashewnuts commented on requirements.txt
> +celery==4.1.0
ASK: パッケージ配布にrequirements.txt入りますか？setup.pyのinstall_requireに書く内容だと思いました。

2022-03-10 06:16 UTC, tell-k commented on requirements.txt
> +celery==4.1.0
なんたのめの requirements.txt なのか簡単に説明を書いておいてあげると良いと思いました。パッケージに必要ないのであれば、ない方が混乱は少なさそうな気がしまた。

2022-03-10 07:01 UTC, imaxyz commented on .github/workflows/tests.yml
> +        python-version: [3.6, 3.9]
tox.iniとREADMEから2.7のサポート記述を外しました。

「bpmailerから2.7サポート外そう」という議論は経ていませんが、他のパッケージにならってpy2.7サポートを外してみました。

2022-03-10 07:02 UTC, kashewnuts commented on README.md
SHOULD: travisの結果を見ているのでGitHub Action版に変更してください。

2022-03-10 07:09 UTC, imaxyz commented on README.md
修正しました

2022-03-10 08:11 UTC, imaxyz commented on .github/workflows/tests.yml
> +      matrix:
## ASKの回答

tox-gh-actionsパッケージの仕様と、bpmailerのtox.iniの記述内容から、bpmailerのworkflow/tests.pyには、djangoのmatrixを記述する必要はないと判断しました。

## 理由

作業の際、Workflowが実行したジョブのログを確認したところ、自動でtox.iniに記述した各djangoバージョンのバリエーションテストを実行してくれていたので、matrixには記述しませんでした。

この辺の挙動をよく理解できていなかったため、再調査しました。

### 再調査でわかったこと
tox-gh-actionsパッケージの仕様で、tox.ini の `gh-actions` の項目にPythonバージョンを記述すると、Github Actionのジョブから実行するtoxでは、`gh-actions` に記述した各Pythonバージョンに絞った状態で実行ができる仕様があるようです。

次のドキュメントの例だと、

> On Python 3.9 job, tox runs py39 environment
https://github.com/ymyzk/tox-gh-actions/blob/master/README.md#basic-example

Python3.9のジョブを実行する際には、py39環境にてtoxを実行してくれるようです。


## 考察

試しに、workflows/tests.ymlに次のように記述して見たところ

```
   - name: Test with tox
      run: |
        tox -l  ← 追記
        tox
```

Github Actionsは、tox-gh-actionsのドキュメントの通り、そのジョブで指定されたPythonバージョンに関するテストのバリエーションを実行していることを確認しました。

```
Run tox -l 
py36-django  
py36-django22
GLOB sdist-make: /home/runner/work/bpmailer/bpmailer/setup.py
py36-django111 create: /home/runner/work/bpmailer/bpmailer/.tox/py36-django111
tox: py36-django111
py36-django22 create: /home/runner/work/bpmailer/bpmailer/.tox/py36-django22
tox: py36-django22
___________________________________ summary ____________________________________
  py36-django111: commands succeeded
  py36-django22: commands succeeded
  congratulations :)
```

https://github.com/beproud/bpmailer/runs/5492233415?check_suite_focus=true

## 備考

workflowに追加した、tox -lのコマンドは今後コードを確認する人が動作を把握するのに役立つと思ったので、一旦そのまま残しました。

2022-03-10 08:19 UTC, shimizukawa commented on .github/workflows/tests.yml
> +      matrix:
@imaxyz matrix化することによって順次実行ではなく並列実行になります。また Python x Django の組合せ名でテスト実行記録が残るためエラー発生時に原因が追いやすくなります。この機会にそのように構成したほうが良いとおもいますが、どうでしょうか？

具体的には以下の様になります。

## 現在のこのPRのテスト
![image](https://user-images.githubusercontent.com/151623/157617539-8a5adb51-9bad-499c-9d62-62e099af7ecf.png)

## 別プロジェクトでの例
https://github.com/jazzband/django-redshift-backend/runs/5347475991?check_suite_focus=true 
<img width="1194" alt="image" src="https://user-images.githubusercontent.com/151623/157618104-c7c4b649-e4c1-4ad0-9660-9e78ddf39016.png">

2022-03-10 08:29 UTC, imaxyz commented on requirements.txt
> +celery==4.1.0
回答: このrequirements.txtパッケージには入れなくて良いファイルの認識です。

理由: 
* requirements.txtは、bpmailerのPythonコードをメンテする人向けに追加しました。
* [tell-kさんのコメント](https://github.com/beproud/bpmailer/pull/13/files#r823377585)を見て、たしかにと思ったので、requirements.txtに、何のために存在するファイルなのかのコメントを追加しました。

2022-03-10 08:30 UTC, imaxyz commented on requirements.txt
> +celery==4.1.0
requirements.txtにコメントを追加しました。

2022-03-11 03:39 UTC, imaxyz commented on tests.py
> +    failures = test_runner.run_tests(['beproud.django.mailer.tests'])
現在 bpmailerのtoxがfailする原因について
-----------------------------------------------

@kashewnuts 

* [頂いたコメント](https://github.com/beproud/bpmailer/pull/13/files#r823374974)に関して、py36, py39共に、bpmailerのtox.iniの `testenv - deps` の項目に、次の行を追加することでtoxから実行する単体テストがpassすることを確認しました。

```
setuptools<=51.1.2
```

※ [この改修](https://github.com/pypa/setuptools/issues/2493)がsetuptoolsの51.1.2の次のバージョンである51.2.0でマージされたことも[確認しました](https://github.com/pypa/setuptools/blob/main/CHANGES.rst#v5120)

このことから、今回の作業でbpmailerのtoxがfailしている原因は、setuptoolsが、bpmailerをpy36対応した時の作業の時と比べてバージョンアップしていて、動作が変わっていたことが原因と思いました。


`python setup.py test` コマンドが非推奨の件
---------------------------------------------------------------

@kashewnuts 

#14 でissueにしました。別PRで対応できればと思います。

今回の改修方法の妥当性について
-----------------------------------

@shimizukawa 

> (Djangoのバージョンが変わったためか?)

最初上記のようにコメントしたのですが、上述のsetuptoolsの調査結果から、Djnagoのバージョンは関係なさそうです。

[setuptoolsの改修で使われているメソッド](https://github.com/pypa/setuptools/pull/2523/files#diff-e3d3d454fa3a072c9f46f8affa27513892fbc2d245e87f57a5927a7be851de05)の差分について調べられたらベストなのですが、まだ調べられていません。

改修方法の妥当性について、確信は無いのですが、[bpmailerが使用するバージョンのDjnagoのrun_tests()のコメント](https://github.com/django/django/blob/e541f2d05b88e58c18b82b622aacc38d670eb5f6/django/test/runner.py#L618)に

> Test labels should be dotted Python paths to test modules, test classes, or test methods.
> 意訳: ラベルは「テストモジュールか、テストクラスか、テストメソッド」にすべき

と書かれているのに対して、テストモジュールの上位のパッケージ名(mailer)を指定していることから、Djangoが想定するシグニチャに沿った実装に近づける意味で、適切ではと考えました。

```
# before
test_runner.run_tests(['beproud.django.mailer'])

# after
test_runner.run_tests(['beproud.django.mailer.tests'])
```

あと、tox.iniのdeps項目に、setuptoolsのバージョンを指定すべきか？を考えました。

現在の改修方法だと、setuptoolsのバージョンが51.2.0未満でも51.2.0以上でもtoxがpassしました。
なので、tox.iniにsetuptoolsのバージョン指定を記述する必要ないと考えました。

2022-03-11 05:38 UTC, imaxyz commented on .github/workflows/tests.yml
> +      matrix:
並列化しました。

Python 2.7とDjango 1.11をdropしたため、このPRでは並列化の効果が高くありませんが、今後のPRで恩恵を受けられるので、workflowを並列化する記述に修正しました。

2022-03-11 05:40 UTC, imaxyz commented on tox.ini
> +envlist = py27-django111, py36-django{111,22}, py39-django22
Python 2.7と、Django 1.11をdropしました。

2022-03-11 05:52 UTC, kemu3007 commented on .github/workflows/tests.yml
> +        python-version: ['3.6', '3.9']
3.6はすでにEOLです。3.7に修正して良さそう

2022-03-11 05:54 UTC, shimizukawa requested changes
レビューしました

2022-03-11 05:54 UTC, shimizukawa commented on .github/workflows/tests.yml
> +      max-parallel: 4
ASK: これ要りますか？（制限しているのを初めて見た）

無指定にして、実行環境で使えるだけ使えばよいのでは。

2022-03-11 05:54 UTC, shimizukawa commented on requirements.txt
> +# toxを使用せず、直接 python tests.py で単体テスト実行する際に pip installするパッケージ一覧です。
SHOULD: ファイル名を `requirements-test.txt` 等にして、テストでのみ必要という意味を持たせて欲しい。

2022-03-11 05:54 UTC, shimizukawa commented on tests.py
> +    failures = test_runner.run_tests(['beproud.django.mailer.tests'])
OKです。別PRでtest.pyを削除するのであれば、問題ないです。

2022-03-11 05:54 UTC, shimizukawa commented on tox.ini
> -  1.11: django111
MUST: 1.11をドロップしたのであれば、setup.pyも更新してください。

https://github.com/beproud/bpmailer/blob/e44f6b40eb2125a7ac8cc426f8aa1f186d77b3e8/setup.py#L63

以下、ついでに依頼です。
classifiers も更新お願いします。

https://github.com/beproud/bpmailer/blob/e44f6b40eb2125a7ac8cc426f8aa1f186d77b3e8/setup.py#L51-L59

参考記述

https://github.com/jazzband/django-redshift-backend/blob/6b862eca2e1c6d5f66fe0dd4e1646be573256f59/setup.cfg#L15-L25

2022-03-11 05:54 UTC, imaxyz commented on .github/workflows/tests.yml
> +        python-version: ['3.6', '3.9']
@kemu3007 このbpmailerを使いたいプロジェクトがまだPython3.6を使っているため、現時点ではPython3.6対応は残したい感じです。

2022-03-11 06:06 UTC, imaxyz commented on requirements.txt
> +# toxを使用せず、直接 python tests.py で単体テスト実行する際に pip installするパッケージ一覧です。
ファイル名を修正しました。

2022-03-11 06:13 UTC, imaxyz commented on tox.ini
> -  1.11: django111
setup.pyの記述内容を修正しました。

2022-03-11 06:19 UTC, shimizukawa approved these changes
LGTM + 1つ「できれば」依頼

2022-03-11 06:19 UTC, shimizukawa commented on setup.py
> +    install_requires=['Django>=2.2', 'six'],
すみません、もう1個思い出しました。
できれば対応お願いします。

Py2 drop するのであれば、 `python_requires` で3.6以上を指定して下さい。
https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#python-requires

例
https://github.com/jazzband/django-redshift-backend/blob/master/setup.cfg#L36

2022-03-11 06:27 UTC, imaxyz commented on README.md
補足
--------

Markdownだとsvg画像へリンクする記述方法しか見当たりませんでした。

https://docs.github.com/ja/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge

バッチアイコンを選択して、バッチの画像をダウンロードするよりか、より情報が多いWebページに遷移した方が良いと考え、rstに変更してみました

2022-03-11 06:34 UTC, kashewnuts approved these changes
LGTM with nits. 直近の作業には影響しないレベルだと思います。

2022-03-11 06:34 UTC, kashewnuts commented on .github/workflows/tests.yml
> +        tox -l
マトリクス対応したので `-l` は不要な認識です。削除してください。  https://github.com/beproud/bpmailer/pull/13/files#r824402013
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/1122795/157812673-05d62bd9-ba04-47e2-9810-ef8253f5b5e6.png">

2022-03-11 06:34 UTC, kashewnuts commented on requirements-test.txt
> +# toxを使用せず、直接 python tests.py で単体テスト実行する際に pip installするパッケージ一覧です。
IMO: この後Django3.2対応もあると思うので、Django2.2固定のこのファイルは削除することになると思います。なのでこのPRでは一旦よいかもしれませんが、後々は削除したほうが第三者が混乱しなくてよさそうです。

2022-03-11 06:34 UTC, kashewnuts commented on setup.py
> +    install_requires=['Django>=2.2', 'six'],
依存で必要とREADMEにもrequirements.txtにも記載しているので必要かと思います。
```suggestion
    install_requires=['Django>=2.2', 'six', 'celery'],
```

2022-03-11 06:34 UTC, kashewnuts commented on tox.ini
> +envlist = py36-django22, py39-django22
nits: 書き方を省略できます https://github.com/beproud/bpmailer/pull/13#discussion_r823374085

2022-03-11 06:35 UTC, imaxyz commented on setup.py
> +    install_requires=['Django>=2.2', 'six'],
追記しました

2022-03-11 06:39 UTC, imaxyz commented on tox.ini
> +envlist = py36-django22, py39-django22
suggestionを見落としていました。

修正しました。

2022-03-11 06:43 UTC, imaxyz commented on requirements-test.txt
> +# toxを使用せず、直接 python tests.py で単体テスト実行する際に pip installするパッケージ一覧です。
なるほどです。ryです。今回は残しておきます。

2022-03-11 06:43 UTC, imaxyz commented on .github/workflows/tests.yml
> +        tox -l
削除しました

2022-03-11 07:30 UTC, merged