bump up version number to 1.2
beproud/bpmailer pull request #16
Opened 2022-03-15 03:33 UTC by imaxyz

setup.pyのバージョン番号を、次回リリースのバージョン番号に変更しました。

2022-03-15 06:07 UTC, shimizukawa requested changes
このPRそのものとしては、LGTMです。
動作確認として、test.pypi.org にアップロードして、そのリンクを貼って下さい。
うまくいけば、CI結果のバッヂも含め期待通りに表示されるはずですが、それをレビューする場がないので、このPR上で確認させてください。

2022-03-16 08:27 UTC, imaxyz commented
@shimizukawa 

TestPyPIでアップロードを試したところ、いくつか修正すべき箇所を発見したため、修正しました。

次のリンクで、CIの結果のバッヂが期待通りに表示されることを確認しました。

https://test.pypi.org/project/bpmailer/1.2.post3/

2022-03-16 08:30 UTC, shimizukawa approved these changes
LGTM.

今回得た知識をリリース手順としてまとめてくれると嬉しいです。
参考: https://github.com/beproud/django-newauth/blob/master/checklist.rst

2022-03-16 08:34 UTC, imaxyz commented
別PRで、bpmailerのchecklist.rstを作ります。

2022-03-16 08:34 UTC, merged