bpmailerのPyPIへのリリース手順を記述するchecklistを追加
beproud/bpmailer pull request #17
Opened 2022-03-16 09:02 UTC by imaxyz

# 対応内容

* bpmailerのリリース手順を release_checklist.rstにまとめて、追加しました。

https://github.com/beproud/bpmailer/blob/add-checklist/checklist.rst

# レビューしてほしい点

* リリース手順に間違いがないか
* 冗長な書き方や、記述が不足している点はないか
* 保守対象の文章として適切な文章か
* Readmeに release_checklist.rst のリンクの記述したのですが、次の対応で違和感ないかもご意見いただきたいです。
  * https://github.com/beproud/bpmailer/pull/17#discussion_r832825970

2022-03-18 09:00 UTC, posbin reviewed
@imaxyz レビューしてコメントしました。ご確認をお願いします

2022-03-18 09:00 UTC, posbin commented on checklist.rst
> +   * ``twine check --strict dist/*``
メモ: https://twine.readthedocs.io/en/stable/#twine-check

2022-03-18 09:00 UTC, posbin commented on checklist.rst
> +5. もしTestPyPIでの表示が正しくない場合、下記の「備考」を参考にパッケージのバージョンを変更して再度アップロードする
[IMO] 「表示を確認する」は description のことだと思いますが、主語がないので漠然すぎるのと、TestPyPIを使う目的は description の体裁の確認だけでなく、ビルドしたパッケージがちゃんとアップロードされていることの確認も含まれると思うので、以下のように書いておくのが良さそうに思いました

```suggestion
4. TestPyPIでdescriptionが正しく表示されていること、ビルドしたパッケージがアップロードされていることを確認する
5. もしTestPyPIでのアップロードに失敗していた場合、下記の「備考」を参考にパッケージのバージョンを変更して再度アップロードする
```

2022-03-18 09:00 UTC, posbin commented on checklist.rst
> +7. Githubで次バージョンのRelaseタグを作成して、Publish Releaseする
[nits] typo

```suggestion
7. Githubで次バージョンのReleaseタグを作成して、Publish Releaseする
```

2022-03-18 09:00 UTC, posbin commented on checklist.rst
> +* ``python setup.py egg_info --tag-build=postN sdist bdist_wheel``
メモ: https://setuptools.pypa.io/en/latest/userguide/commands.html#release-tagging-options

2022-03-18 09:00 UTC, posbin commented on checklist.rst
> +   * ``pip install Django~=2.2 Celery~=4.1 six``
[ASK] このあたりのパッケージは install_requires に書いているので、この個別にパッケージインストールするコマンドは手順に不要ではないでしょうか？

https://github.com/beproud/bpmailer/blob/master/setup.py#L68

2022-03-18 09:09 UTC, kashewnuts requested changes

2022-03-18 09:09 UTC, kashewnuts commented on checklist.rst
> +   * ``pip install Django~=2.2 Celery~=4.1 six``
SHOULD: この記述だとCeleryが4系の最新のバージョンになり、READMEに記載したRequirementsと合わなくなるので要件と一致させてください。
```suggestion
   * ``pip install Django~=2.2 Celery~=4.1.0 six``
```

2022-03-18 09:09 UTC, kashewnuts commented on checklist.rst
> +リリース手順
SHOULD: 
* リリース時にこのファイルを見ればいいことがわかるようにREADMEからリンクしてください。
* `release_checklist.rst` のようになんのチェックリストかファイル名を明確にしてください。

2022-03-18 09:09 UTC, kashewnuts commented on checklist.rst
> +* Githubアカウントに、bpmailerの編集権限を付与してもらう
全般的にTypo
```suggestion
* GitHubアカウントに、bpmailerの編集権限を付与してもらう
```

2022-03-18 09:09 UTC, kashewnuts commented on checklist.rst
> +TestPyPIに同じバージョンで、再アップロードしたい時
SHOULD: どうして同じバージョンでアップロードするのかを記述してください。この欄を記述するに至った理由があるはずです。

2022-03-18 09:09 UTC, kashewnuts commented on checklist.rst
> +* TestPyPIのアカウントを取得する
MUST: アカウント取得だけでなく権限の付与も必要なはずです。 https://beproud.slack.com/archives/C028XFALA/p1646815113199879?thread_ts=1646814372.751019&cid=C028XFALA

2022-03-22 07:12 UTC, imaxyz commented on checklist.rst
> +   * ``pip install Django~=2.2 Celery~=4.1 six``
@kashewnuts 

> この記述だとCeleryが4系の最新のバージョンになり

なるほど、その観点が抜けておりました。修正した方が良さそうです。

[確認]
ところで、celeryの4.1系の系列を確認したところ、4.1.1がリリースされていました。

https://pypi.org/project/celery/4.1.1/

この箇所は `Celery~=4.1.1` と記述しておいた方が良いでしょうか？

2022-03-22 07:18 UTC, imaxyz commented on checklist.rst
> +* TestPyPIのアカウントを取得する
toxの権限付与について記載が漏れていました。追記します。

2022-03-22 07:31 UTC, imaxyz commented on checklist.rst
> +TestPyPIに同じバージョンで、再アップロードしたい時
理由の説明を追記しました。

2022-03-22 07:39 UTC, imaxyz commented on checklist.rst
> +リリース手順
READMEにリンクを追加しました。
チェックリストのファイル名を変更しました。

2022-03-22 07:43 UTC, imaxyz commented on checklist.rst
> +   * ``pip install Django~=2.2 Celery~=4.1 six``
suggestionの内容で意図した挙動になることを確認しました。修正します。

2022-03-22 08:01 UTC, imaxyz commented on checklist.rst
> +   * ``pip install Django~=2.2 Celery~=4.1 six``
この箇所の記述に関して、次の理由から、残しておきたいと思いました。いかがでしょうか？

理由: 

* この手順を記述しておくことで、setup.pyのinstall_requiresの箇所を確認する慣習がまだ身に付いていない開発者でも、ハマらずに確実にリリース作業を実施実行できるため。
  * 実際、私は結果として事前知識が不足した状態で作業に着手したため、setup.pyの install_requires の確認が漏れており、原因の調査に時間を使ってしまいました。
* 見る人によっては冗長に見えるかもしれませんが、明示的に記述しておくことで、誰でもハマることなくリリース作業を進めることができるため。
  * この記述箇所のバージョン番号を今後も保守する責務は生まれてしまいますが、今後、誰かがこの箇所の把握の不足でハマることを抑止できるので、残しておいても良いかなと思いました。

2022-03-23 01:02 UTC, shimizukawa requested changes
ファイルの情報が「手順」と「テクニック」の混合になっています。
情報を手順に絞って下さい。

この路線でBPが扱う複数のパッケージにこの手順を書き始めると、それぞれで手順のメンテナンスコストがかかるし、行数自体長いので細かな派生版が各パッケージで生まれてしまいます。
テクニックを残したいのであれば、別ファイルやWiki等に分離してください。

2022-03-23 01:02 UTC, shimizukawa commented on README.rst
> +* `release checklist </release_checklist.rst>`_
ASK: このリンクは、PyPI上でどのように表示されますか？

GitHub上では機能してますが、PyPIではリンク切れになると思います。

2022-03-23 01:02 UTC, shimizukawa commented on release_checklist.rst
> +2. twineのコマンドを実行して、PyPIでパッケージのドキュメントを正しく表示できそうか確認する
ASK

> 正しく表示できそうか

「正しい」とは何ですか？このコマンドにおける正しさを定義してください。
「表示できそう」の判断基準はなんですか？判断基準を定義してください。

checkでエラーがでないこと、で良いのでは？

2022-03-23 01:02 UTC, shimizukawa commented on release_checklist.rst
> +   * ``python -m twine upload --repository testpypi dist/*``
ASK: 2番では `twine` コマンドを使ったのに、 3版では `python -m twine` としている意図はありますか？

2022-03-23 01:02 UTC, shimizukawa commented on release_checklist.rst
> +4. TestPyPIでdescriptionが正しく表示されていること、ビルドしたパッケージがアップロードされていることを確認する
ASK 「正しく表示」とはどんな状態ですか？

2022-03-23 01:02 UTC, shimizukawa commented on release_checklist.rst
> +5. もしTestPyPIでのアップロードが失敗していた場合、下記の「備考」を参考にパッケージのバージョンを変更して再度アップロードする
MAY: 5番は4の子要素な気がします。

2022-03-23 01:02 UTC, shimizukawa commented on release_checklist.rst
> +   * ``pip install Django~=2.2 Celery~=4.1.0 six``
SHOULD: この行は不要です。

理由は以下の通り。

* bpmailerのinstall_requiresに依存が定義されているため、自動でインストールされる
* bpmailerのインストールが期待通りに行えるかどうかと、この3つの依存パッケージを先にインストールすることは関係がない
* 依存パッケージがこことsetup.pyとで複数箇所に登場するため保守忘れが発生しやすくなる

2022-03-23 01:02 UTC, shimizukawa commented on release_checklist.rst
> +   * ``pip freeze | grep bpmailer``
nits: 確認したいなら `pip show bpmailer` でよさそう。このままでも問題はないです

2022-03-23 01:02 UTC, shimizukawa commented on release_checklist.rst
> +   * ``python setup.py sdist bdist_wheel``
ASK: ちょっと意味が分かりません。パッケージ名を変更する手順がありましたか？

2022-03-23 01:02 UTC, shimizukawa commented on release_checklist.rst
> +   * ``python -m twine upload dist/*``
ASK: `dist/` 以下のクリーニングは不要でしょうか？

試行錯誤して作られたパッケージファイルが `dist/` に残っていると、それらが全てアップロード対象になります。

2022-03-23 01:02 UTC, shimizukawa commented on release_checklist.rst
> +* ``python setup.py egg_info --tag-build=postN sdist bdist_wheel``
MUST: このファイル内には不要な情報です。

こはリリース手順ではなく「PyPIリリーステクニック」です。

2022-03-23 01:02 UTC, shimizukawa commented on release_checklist.rst
> +* GitHubアカウントに、bpmailerの編集権限を付与してもらう
MAY: 1行にまとめてください。

3行書いてあるけど、言っていることは3つとも「アカウント用意、権限付与」です。
分かっている人には不要な情報だし、分からない人は「アカウント取得方法は？」「権限は誰に付与してもらう？」などさらに疑問が出てくるため、長く書く必要がなさそうです。

この3行全部不要とも思いますが、書きたい場合は以下の1行で十分でしょう。

```suggestion
* GitHub, PyPI, TestPyPIのアカウントにbpmailerの編集権限を設定
```

2022-03-23 02:25 UTC, imaxyz commented on README.rst
> +* `release checklist </release_checklist.rst>`_
TestPyPIにアップロードしてみたところ、表示は意図通りでしたが、リンク先が不適切でした。修正します。

https://test.pypi.org/release_checklist.rst

![image](https://user-images.githubusercontent.com/23151008/159611502-47fc0cfe-46fc-4bed-9063-bde718a52dfb.png)

2022-03-23 02:56 UTC, imaxyz commented on README.rst
> +* `release checklist </release_checklist.rst>`_
リンク先を https://github.com/beproud/bpmailer/blob/master/release_checklist.rst に変更しました。

2022-03-23 03:30 UTC, imaxyz commented on release_checklist.rst
> +2. twineのコマンドを実行して、PyPIでパッケージのドキュメントを正しく表示できそうか確認する
「正しい」という表現は曖昧で今回は定義しきれないので、「エラーがでないこと」という表現に訂正しました。

2022-03-23 03:31 UTC, imaxyz commented on release_checklist.rst
> +   * ``python -m twine upload --repository testpypi dist/*``
python -m の記述を全体的に削除しました。

2022-03-23 03:32 UTC, imaxyz commented on release_checklist.rst
> +4. TestPyPIでdescriptionが正しく表示されていること、ビルドしたパッケージがアップロードされていることを確認する
上述と同様に「エラーなく表示」という表現に訂正しました。

2022-03-23 03:33 UTC, imaxyz commented on release_checklist.rst
> +5. もしTestPyPIでのアップロードが失敗していた場合、下記の「備考」を参考にパッケージのバージョンを変更して再度アップロードする
その通りと思ったので、入れ子に変更しました。

2022-03-23 03:34 UTC, imaxyz commented on release_checklist.rst
> +   * ``pip freeze | grep bpmailer``
`pip show bpmailer` の方が情報量が多くて良いと思ったので修正しました。

```
% pip show bpmailer
Name: bpmailer
Version: 1.2.post3
Summary: Mailing utility for Django
Home-page: https://github.com/beproud/bpmailer/
Author: BeProud Inc.
Author-email: project@beproud.jp
License: UNKNOWN
Location: /<path>/venv/lib/python3.7/site-packages
Requires: Celery, Django, six
Required-by: 

```

2022-03-23 03:35 UTC, imaxyz commented on release_checklist.rst
> +   * ``python setup.py sdist bdist_wheel``
記述足らずでしたので表現を変更しました。

2022-03-23 03:36 UTC, imaxyz commented on release_checklist.rst
> +   * ``python -m twine upload dist/*``
`dist/` 配下のクリーニング作業は、スムーズなリリース作業にとって大切と思ったので追記しました。

2022-03-23 03:36 UTC, imaxyz commented on release_checklist.rst
> +* ``python setup.py egg_info --tag-build=postN sdist bdist_wheel``
ryです。削除しました。

2022-03-23 03:58 UTC, imaxyz commented on README.rst
> +* `release checklist <https://github.com/beproud/bpmailer/blob/master/release_checklist.rst>`_
masterブランチに、 release_checklist.rst が配置されている前提のリンクです。

他にうまい書き方が思いつきませんでした。

（無くても良い気もしてきた

2022-03-23 04:38 UTC, shimizukawa commented on README.rst
> +* `release checklist </release_checklist.rst>`_
OK

2022-03-23 04:38 UTC, shimizukawa commented on release_checklist.rst
> +2. twineのコマンドを実行して、PyPIでパッケージのドキュメントを正しく表示できそうか確認する
OK

2022-03-23 04:38 UTC, shimizukawa commented on release_checklist.rst
> +   * ``python -m twine upload --repository testpypi dist/*``
OK

2022-03-23 04:38 UTC, shimizukawa commented on release_checklist.rst
> +4. TestPyPIでdescriptionが正しく表示されていること、ビルドしたパッケージがアップロードされていることを確認する
OK

2022-03-23 04:38 UTC, shimizukawa commented on release_checklist.rst
> +5. もしTestPyPIでのアップロードが失敗していた場合、下記の「備考」を参考にパッケージのバージョンを変更して再度アップロードする
OK

2022-03-23 04:38 UTC, shimizukawa commented on release_checklist.rst
> +   * ``pip install Django~=2.2 Celery~=4.1.0 six``
@imaxyz  対応しないとしてもコメント欲しいです

2022-03-23 04:38 UTC, shimizukawa commented on release_checklist.rst
> +   * ``pip freeze | grep bpmailer``
OK

2022-03-23 04:38 UTC, shimizukawa commented on release_checklist.rst
> +* ``python setup.py egg_info --tag-build=postN sdist bdist_wheel``
KO

2022-03-23 04:41 UTC, shimizukawa commented on checklist.rst
> +   * ``pip install Django~=2.2 Celery~=4.1 six``
理由に納得出来ません。
その論理展開で行くと、Pythonを初めて触る人のためにPythonのインストール方法から説明が必要になります。

確認ですが、この行がなくても結果は変わらないですよね？

2022-03-23 05:19 UTC, imaxyz commented on release_checklist.rst
> +   * ``pip install Django~=2.2 Celery~=4.1.0 six``
上記に関しては、上記のpip install を実行しないと、期待するbpmailer 1.2 がインストールされず、bpmailer 1.1がインストールされてしまったように思ったので必要だと思って書きました。

（もしかして、私の確認の仕方が誤っている？）

> 保守忘れが発生しやすくなる

はい、書かなくてもリリース手順として不足ないことがわかれば、削除したいと思いました。

2022-03-23 08:34 UTC, imaxyz commented on checklist.rst
> +   * ``pip install Django~=2.2 Celery~=4.1 six``
上の箇所の記述については、slackで以下の議論をして、 **削除する** ことにしました。 

------------

* TestPyPIはリリースの本筋ではない
* TestPyPIでは依存関係解決ができないのでインストール確認に裏技が必要になる
  * TestPyPIには、TestPyPIにアップロードしたbpmailerが期待するバージョンのceleryがアップされていなかったため、期待通りのバージョンのbpmailerをインストールできなかった 
* TestPyPIでリリース確認しておくと安心

↓
* TestPyPIへのアップロード確認の記述は残す
* インストール確認まではリリース手順には書かない

2022-03-23 08:48 UTC, shimizukawa approved these changes
SHOULD1つあり。他は良さそうです

2022-03-23 08:48 UTC, shimizukawa commented on release_checklist.rst
> +   * dist/にpostNバージョンがついたパッケージが残っている場合、それらのパッケージを全て削除し、本番アップロード用のパッケージを再度作成
SHOUDL: `postN` が突然出てくるので表現を変えた方が良さそう

```suggestion
   * dist/に試行錯誤したパッケージが残っている場合、一度全て削除し、本番アップロード用のパッケージを再度作成
```

2022-03-23 09:00 UTC, imaxyz commented on release_checklist.rst
> +   * dist/にpostNバージョンがついたパッケージが残っている場合、それらのパッケージを全て削除し、本番アップロード用のパッケージを再度作成
@shimizukawa 良いと思ったのでsuggestionの内容を反映しました。

2022-03-24 01:17 UTC, posbin approved these changes
@imaxyz LGTM with nits

2022-03-24 01:17 UTC, posbin commented on release_checklist.rst
> +* パッケージのビルドに使用パッケージをインストール
[nits]

```suggestion
* パッケージのビルドに使用するパッケージをインストール
```

2022-03-24 01:45 UTC, merged